export const BUSINESS_GET = "BUSINESS_GET";
export const BUSINESS_GET_SUCCESS = "BUSINESS_GET_SUCCESS";
export const BUSINESS_GET_FAIL = "BUSINESS_GET_FAIL";

export const BUSINESS_ADD_USER = "BUSINESS_ADD_USER";
export const BUSINESS_ADD_USER_SUCCESS = "BUSINESS_ADD_USER_SUCCESS";
export const BUSINESS_ADD_USER_FAIL = "BUSINESS_ADD_USER_FAIL";
