export const CHAT_GET_STREAM_CONNECT = "CHAT_GET_STREAM_CONNECT";
export const CHAT_GET_STREAM_CONNECT_SUCCESS =
  "CHAT_GET_STREAM_CONNECT_SUCCESS";
export const CHAT_GET_STREAM_CONNECT_FAIL = "CHAT_GET_STREAM_CONNECT_FAIL";
export const CHAT_GET_STREAM_CONNECT_RESET = "CHAT_GET_STREAM_CONNECT_RESET";

export const CHAT_GET_STREAM_DISCONNECT_SUCCESS =
  "CHAT_GET_STREAM_DISCONNECT_SUCCESS";

export const DOWNLOAD_FILE_REQUEST = "DOWNLOAD_FILE_REQUEST";
export const DOWNLOAD_FILE_SUCCESS = "DOWNLOAD_FILE_SUCCESS";
export const DOWNLOAD_FILE_ERROR = "DOWNLOAD_FILE_ERROR";
export const DOWNLOAD_FILE_RESET = "DOWNLOAD_FILE_RESET";

export const CHAT_SNACKBAR_TEXT_RESET = "CHAT_SNACKBAR_TEXT_RESET";

export const CHAT_ROOM_LIST = "CHAT_ROOM_LIST";
export const CHAT_ROOM_LIST_SUCCESS = "CHAT_ROOM_LIST_SUCCESS";
export const CHAT_ROOM_LIST_FAIL = "CHAT_ROOM_LIST_FAIL";
export const CHAT_ROOM_LIST_RESET = "CHAT_ROOM_LIST_RESET";

export const CHAT_GET_CONNECTIONS = "CHAT_GET_CONNECTIONS";
export const CHAT_GET_CONNECTIONS_SUCCESS = "CHAT_GET_CONNECTIONS_SUCCESS";
export const CHAT_GET_CONNECTIONS_FAIL = "CHAT_GET_CONNECTIONS_FAIL";

export const CHAT_CREATE_ROOM = "CHAT_CREATE_ROOM";
export const CHAT_CREATE_ROOM_SUCCESS = "CHAT_CREATE_ROOM_SUCCESS";
export const CHAT_CREATE_ROOM_FAIL = "CHAT_CREATE_ROOM_FAIL";

export const CHAT_ADD_USERS = "CHAT_ADD_USERS";
export const CHAT_ADD_USERS_SUCCESS = "CHAT_ADD_USERS_SUCCESS";
export const CHAT_ADD_USERS_FAIL = "CHAT_ADD_USERS_FAIL";

export const CHAT_FETCH_ATTACHMENTS = "CHAT_FETCH_ATTACHMENTS";
export const CHAT_FETCH_ATTACHMENTS_SUCCESS = "CHAT_FETCH_ATTACHMENTS_SUCCESS";
export const CHAT_FETCH_ATTACHMENTS_FAIL = "CHAT_FETCH_ATTACHMENTS_FAIL";

export const CHAT_UPDATE_ROOM = "CHAT_UPDATE_ROOM";
export const CHAT_UPDATE_ROOM_SUCCESS = "CHAT_UPDATE_ROOM_SUCCESS";
export const CHAT_UPDATE_ROOM_FAIL = "CHAT_UPDATE_ROOM_FAIL";

export const CHAT_REMOVE_USER = "CHAT_REMOVE_USER";
export const CHAT_REMOVE_USER_SUCCESS = "CHAT_REMOVE_USER_SUCCESS";
export const CHAT_REMOVE_USER_FAIL = "CHAT_REMOVE_USER_FAIL";

export const CHAT_FETCH_ROOM = "CHAT_FETCH_ROOM";
export const CHAT_FETCH_ROOM_SUCCESS = "CHAT_FETCH_ROOM_SUCCESS";
export const CHAT_FETCH_ROOM_FAIL = "CHAT_FETCH_ROOM_FAIL";
