export const CRM_USER_CHECK = "CRM_USER_CHECK";
export const CRM_USER_CHECK_SUCCESS = "CRM_USER_CHECK_SUCCESS";
export const CRM_USER_CHECK_ERROR = "CRM_USER_CHECK_ERROR";

export const CRM_LEAD_ADD = "CRM_LEAD_ADD";
export const CRM_LEAD_ADD_SUCCESS = "CRM_LEAD_ADD_SUCCESS";
export const CRM_LEAD_ADD_ERROR = "CRM_LEAD_ADD_ERROR";
