export const SUBMIT_FEEDBACK = "SUBMIT_FEEDBACK";
export const SUBMIT_FEEDBACK_SUCCESS = "SUBMIT_FEEDBACK_SUCCESS";
export const SUBMIT_FEEDBACK_FAIL = "SUBMIT_FEEDBACK_FAIL";
export const SUBMIT_FEEDBACK_RESET = "SUBMIT_FEEDBACK_RESET";
