export const GROUP_LIST = "GROUP_LIST";
export const GROUP_LIST_SUCCESS = "GROUP_LIST_SUCCESS";
export const GROUP_LIST_FAIL = "GROUP_LIST_FAIL";

export const GROUP_CREATE_PRIVATE = "GROUP_CREATE_PRIVATE";
export const GROUP_CREATE_PRIVATE_SUCCESS = "GROUP_CREATE_PRIVATE_SUCCESS";
export const GROUP_CREATE_PRIVATE_FAIL = "GROUP_CREATE_PRIVATE_FAIL";

export const GROUP_CREATE_FORM = "GROUP_CREATE_FORM";
export const GROUP_CREATE_FORM_RESET = "GROUP_CREATE_FORM_RESET";

export const GROUP_ADD = "GROUP_ADD";
export const GROUP_ADD_SUCCESS = "GROUP_ADD_SUCCESS";
export const GROUP_ADD_FAIL = "GROUP_ADD_FAIL";

export const GROUP_LEAVE_REQUEST = "GROUP_LEAVE_REQUEST";
export const GROUP_LEAVE_SUCCESS = "GROUP_LEAVE_SUCCESS";
export const GROUP_LEAVE_FAIL = "GROUP_LEAVE_FAIL";

export const GROUP_EXPAND_NETWORK = "GROUP_EXPAND_NETWORK";
export const GROUP_EXPAND_NETWORK_SUCCESS = "GROUP_EXPAND_NETWORK_SUCCESS";
export const GROUP_EXPAND_NETWORK_FAIL = "GROUP_EXPAND_NETWORK_FAIL";

export const GROUP_REMOVE_FAIL = "GROUP_REMOVE_FAIL";
export const GROUP_REMOVE_SUCCESS = "REMOVE_GROUP_SUCCESS";

export const GROUP_INVITE_USER = "GROUP_INVITE_USER";
export const GROUP_INVITE_USER_SUCCESS = "GROUP_INVITE_USER_SUCCESS";
export const GROUP_INVITE_USER_FAIL = "GROUP_INVITE_USER_FAIL";
export const GROUP_INVITE_USER_RESET = "GROUP_INVITE_USER_RESET";

export const GROUP_FETCH_USERS = "GROUP_FETCH_USERS";
export const GROUP_FETCH_USERS_SUCCESS = "GROUP_FETCH_USERS_SUCCESS";
export const GROUP_FETCH_USERS_FAIL = "GROUP_FETCH_USERS_FAIL";

export const GROUP_SET_SELECTED_GROUP = "GROUP_SET_SELECTED_GROUP";
export const GROUP_RESET_USERS = "GROUP_RESET_USERS";

export const GROUP_DELETE = "GROUP_DELETE";
export const GROUP_DELETE_REQUEST = "GROUP_DELETE_REQUEST";
export const GROUP_DELETE_SUCCESS = "GROUP_DELETE_SUCCESS";
export const GROUP_DELETE_FAIL = "GROUP_DELETE_FAIL";
export const GROUP_DELETE_RESET = "GROUP_DELETE_RESET";
export const GROUP_FETCH_INVITE_CODE = "GROUP_FETCH_INVITE_CODE";
export const GROUP_FETCH_INVITE_CODE_SUCCESS =
  "GROUP_FETCH_INVITE_CODE_SUCCESS";
export const GROUP_FETCH_INVITE_CODE_FAIL = "GROUP_FETCH_INVITE_CODE_FAIL";
export const GROUP_FETCH_INVITE_CODE_REQUEST =
  "GROUP_FETCH_INVITE_CODE_REQUEST";
export const GROUP_FETCH_INVITE_CODE_RESET = "GROUP_FETCH_INVITE_CODE_RESET";

export const GROUP_BRANCH_JOIN_LINK = "GROUP_BRANCH_JOIN_LINK";
export const GROUP_BRANCH_RESET = "GROUP_BRANCH_RESET";

export const GROUP_SHARE_INVITE_LINK = "GROUP_SHARE_INVITE_LINK";
export const GROUP_SHARE_INVITE_LINK_SUCCESS =
  "GROUP_SHARE_INVITE_LINK_SUCCESS";
export const GROUP_SHARE_INVITE_LINK_FAIL = "GROUP_SHARE_INVITE_LINK_FAIL";
export const GROUP_SHARE_INVITE_LINK_OPEN_SHEET =
  "GROUP_SHARE_INVITE_LINK_OPEN_SHEET";
