export const LEAD_GET = "LEAD_GET";
export const LEAD_GET_SUCCESS = "LEAD_GET_SUCCESS";
export const LEAD_GET_FAIL = "LEAD_GET_FAIL";
export const LEAD_CREATE = "LEAD_CREATE";
export const LEAD_CREATE_SUCCESS = "LEAD_CREATE_SUCCESS";
export const LEAD_CREATE_FAIL = "LEAD_CREATE_FAIL";
export const LEAD_CREATE_RESET = "LEAD_CREATE_RESET";
export const LEAD_LIST = "LEAD_LIST";
export const LEAD_LIST_SUCCESS = "LEAD_LIST_SUCCESS";
export const LEAD_LIST_FAIL = "LEAD_LIST_FAIL";
export const LEAD_CLEAR = "LEAD_CLEAR";

export const CREATE_LEAD = "CREATE_LEAD";
export const CREATE_LEAD_SUCCESS = "CREATE_LEAD_SUCCESS";
export const CREATE_LEAD_FAIL = "CREATE_LEAD_FAIL";

export const LEAD_LIST_NEW = "LEAD_LIST_NEW";
export const LEAD_LIST_NEW_SUCCESS = "LEAD_LIST_NEW_SUCCESS";
export const LEAD_LIST_NEW_FAIL = "LEAD_LIST_NEW_FAIL";

export const LEAD_LIST_NEARBY = "LEAD_LIST_NEARBY";
export const LEAD_LIST_NEARBY_SUCCESS = "LEAD_LIST_NEARBY_SUCCESS";
export const LEAD_LIST_NEARBY_FAIL = "LEAD_LIST_NEARBY_FAIL";

export const LEAD_DELETE = "LEAD_DELETE";
export const LEAD_DELETE_SUCCESS = "LEAD_DELETE_SUCCESS";
export const LEAD_DELETE_FAIL = "LEAD_DELETE_FAIL";
export const RESET_DELETE_LEAD = "RESET_DELETE_LEAD";
