export const NOTIFICATION_BACKGROUND_TASK = "NOTIFICATION_BACKGROUND_TASK";

export const NOTIFICATION_SET_HANDLER = "NOTIFICATION_SET_HANDLER";
export const NOTIFICATION_SET_HANDLER_SUCCESS =
  "NOTIFICATION_SET_HANDLER_SUCCESS";
export const NOTIFICATION_SET_HANDLER_ERROR = "NOTIFICATION_SET_HANDLER_ERROR";

export const NOTIFICATION_GET_PUSH_TOKEN_REQUEST =
  "NOTIFICATION_GET_PUSH_TOKEN_REQUEST";
export const NOTIFICATION_GET_PUSH_TOKEN_SUCCESS =
  "NOTIFICATION_GET_PUSH_TOKEN_SUCCESS";
export const NOTIFICATION_GET_PUSH_TOKEN_ERROR =
  "NOTIFICATION_GET_PUSH_TOKEN_ERROR";

export const NOTIFICATION_GET_SETTINGS_REQUEST =
  "NOTIFICATION_GET_SETTINGS_REQUEST";
export const NOTIFICATION_GET_SETTINGS_SUCCESS =
  "NOTIFICATION_GET_SETTINGS_SUCCESS";
export const NOTIFICATION_GET_SETTINGS_ERROR =
  "NOTIFICATION_GET_SETTINGS_ERROR";

export const NOTIFICATION_TOGGLE_SETTINGS_REQUEST =
  "NOTIFICATION_TOGGLE_SETTINGS_REQUEST";
export const NOTIFICATION_TOGGLE_SETTINGS_SUCCESS =
  "NOTIFICATION_TOGGLE_SETTINGS_SUCCESS";
export const NOTIFICATION_TOGGLE_SETTINGS_ERROR =
  "NOTIFICATION_TOGGLE_SETTINGS_ERROR";

export const NOTIFICATION_SEND_PUSH_REQUEST = "NOTIFICATION_SEND_PUSH_REQUEST";
export const NOTIFICATION_SEND_PUSH_SUCCESS = "NOTIFICATION_SEND_PUSH_SUCCESS";
export const NOTIFICATION_SEND_PUSH_ERROR = "NOTIFICATION_SEND_PUSH_ERROR";

export const NOTIFICATION_RECEIVED = "NOTIFICATION_RECEIVED";
export const NOTIFICATION_INTERACTION_RECEIVED =
  "NOTIFICATION_INTERACTION_RECEIVED";

export const NOTIFICATION_APP_ICON_BADGE_COUNT_SET =
  "NOTIFICATION_APP_ICON_BADGE_COUNT_SET";
export const NOTIFICATION_APP_ICON_BADGE_COUNT_SET_SUCCESS =
  "NOTIFICATION_APP_ICON_BADGE_COUNT_SET_SUCCESS";
export const NOTIFICATION_APP_ICON_BADGE_COUNT_SET_ERROR =
  "NOTIFICATION_APP_ICON_BADGE_COUNT_SET_ERROR";

export const NOTIFICATION_APP_ICON_BADGE_COUNT_INCREMENT =
  "NOTIFICATION_APP_ICON_BADGE_COUNT_INCREMENT";
export const NOTIFICATION_APP_ICON_BADGE_COUNT_INCREMENT_SUCCESS =
  "NOTIFICATION_APP_ICON_BADGE_COUNT_INCREMENT_SUCCESS";
export const NOTIFICATION_APP_ICON_BADGE_COUNT_INCREMENT_ERROR =
  "NOTIFICATION_APP_ICON_BADGE_COUNT_INCREMENT_ERROR";

export const NOTIFICATION_APP_ICON_BADGE_COUNT_DECREMENT =
  "NOTIFICATION_APP_ICON_BADGE_COUNT_DECREMENT";
export const NOTIFICATION_APP_ICON_BADGE_COUNT_DECREMENT_SUCCESS =
  "NOTIFICATION_APP_ICON_BADGE_COUNT_DECREMENT_SUCCESS";
export const NOTIFICATION_APP_ICON_BADGE_COUNT_DECREMENT_ERROR =
  "NOTIFICATION_APP_ICON_BADGE_COUNT_DECREMENT_ERROR";

export const NOTIFICATION_APP_ICON_BADGE_COUNT_RESET =
  "NOTIFICATION_APP_ICON_BADGE_COUNT_RESET";
export const NOTIFICATION_APP_ICON_BADGE_COUNT_RESET_SUCCESS =
  "NOTIFICATION_APP_ICON_BADGE_COUNT_RESET_SUCCESS";
export const NOTIFICATION_APP_ICON_BADGE_COUNT_RESET_ERROR =
  "NOTIFICATION_APP_ICON_BADGE_COUNT_RESET_ERROR";
