export const OPPORTUNITY_CREATE_FORM = "OPPORTUNITY_CREATE_FORM";
export const OPPORTUNITY_CREATE_FORM_RESET = "OPPORTUNITY_CREATE_FORM_RESET";

export const OPPORTUNITY_CREATE = "OPPORTUNITY_CREATE";
export const OPPORTUNITY_CREATE_FAIL = "OPPORTUNITY_CREATE_FAIL";
export const OPPORTUNITY_CREATE_RESET = "OPPORTUNITY_CREATE_RESET";
export const OPPORTUNITY_CREATE_SUCCESS = "OPPORTUNITY_CREATE_SUCCESS";

export const OPPORTUNITY_UPDATE = "OPPORTUNITY_UPDATE";
export const OPPORTUNITY_UPDATE_FAIL = "OPPORTUNITY_UPDATE_FAIL";
export const OPPORTUNITY_UPDATE_RESET = "OPPORTUNITY_UPDATE_RESET";
export const OPPORTUNITY_UPDATE_SUCCESS = "OPPORTUNITY_UPDATE_SUCCESS";

export const OPPORTUNITY_CONVERT_LEAD = "OPPORTUNITY_CONVERT_LEAD";
export const OPPORTUNITY_CONVERT_LEAD_FAIL = "OPPORTUNITY_CONVERT_LEAD_FAIL";
export const OPPORTUNITY_CONVERT_LEAD_RESET = "OPPORTUNITY_CONVERT_LEAD_RESET";
export const OPPORTUNITY_CONVERT_LEAD_SUCCESS =
  "OPPORTUNITY_CONVERT_LEAD_SUCCESS";

export const OPPORTUNITY_CURRENT_RESET = "OPPORTUNITY_CURRENT_RESET";

export const OPPORTUNITY_DELETE = "OPPORTUNITY_DELETE";
export const OPPORTUNITY_DELETE_FAIL = "OPPORTUNITY_DELETE_FAIL";
export const OPPORTUNITY_DELETE_SUCCESS = "OPPORTUNITY_DELETE_SUCCESS";

export const OPPORTUNITY_GET = "OPPORTUNITY_GET";
export const OPPORTUNITY_GET_FAIL = "OPPORTUNITY_GET_FAIL";
export const OPPORTUNITY_GET_SUCCESS = "OPPORTUNITY_GET_SUCCESS";

export const OPPORTUNITY_LIST = "OPPORTUNITY_LIST";
export const OPPORTUNITY_LIST_FAIL = "OPPORTUNITY_LIST_FAIL";
export const OPPORTUNITY_LIST_SUCCESS = "OPPORTUNITY_LIST_SUCCESS";

export const OPPORTUNITY_LIST_NEARBY = "OPPORTUNITY_LIST_NEARBY";
export const OPPORTUNITY_LIST_NEARBY_FAIL = "OPPORTUNITY_LIST_NEARBY_FAIL";
export const OPPORTUNITY_LIST_NEARBY_SUCCESS =
  "OPPORTUNITY_LIST_NEARBY_SUCCESS";

export const OPPORTUNITY_INVITE_USER_REQUEST =
  "OPPORTUNITY_INVITE_USER_REQUEST";
export const OPPORTUNITY_INVITE_USER_FAIL = "OPPORTUNITY_INVITE_USER_FAIL";
export const OPPORTUNITY_INVITE_USER_SUCCESS =
  "OPPORTUNITY_INVITE_USER_SUCCESS";
export const OPPORTUNITY_INVITE_USER_RESET = "OPPORTUNITY_INVITE_USER_RESET";

export const OPPORTUNITY_GET_INVITE_CODE_REQUEST =
  "OPPORTUNITY_GET_INVITE_CODE_REQUEST";
export const OPPORTUNITY_GET_INVITE_CODE_FAIL =
  "OPPORTUNITY_GET_INVITE_CODE_FAIL";
export const OPPORTUNITY_GET_INVITE_CODE_SUCCESS =
  "OPPORTUNITY_GET_INVITE_CODE_SUCCESS";
export const OPPORTUNITY_GET_INVITE_CODE_RESET =
  "OPPORTUNITY_GET_INVITE_CODE_RESET";

export const OPPORTUNITY_SHARE_LINK = "OPPORTUNITY_SHARE_LINK";
export const OPPORTUNITY_SHARE_LINK_FAIL = "OPPORTUNITY_SHARE_LINK_FAIL";
export const OPPORTUNITY_SHARE_LINK_SUCCESS = "OPPORTUNITY_SHARE_LINK_SUCCESS";
export const OPPORTUNITY_SHARE_LINK_OPEN_SHEET =
  "OPPORTUNITY_SHARE_LINK_OPEN_SHEET";
export const OPPORTUNITY_SHARE_LINK_RESET = "OPPORTUNITY_SHARE_LINK_RESET";

export const OPPORTUNITY_BRANCH_JOIN_LINK = "OPPORTUNITY_BRANCH_JOIN_LINK";
export const OPPORTUNITY_BRANCH_JOIN_LINK_RESET =
  "OPPORTUNITY_BRANCH_JOIN_LINK_RESET";

export const OPPORTUNITY_INVITE_ACCEPTED_REQUEST =
  "OPPORTUNITY_INVITE_ACCEPTED_REQUEST";
export const OPPORTUNITY_INVITE_ACCEPTED_FAIL =
  "OPPORTUNITY_INVITE_ACCEPTED_FAIL";
export const OPPORTUNITY_INVITE_ACCEPTED_SUCCESS =
  "OPPORTUNITY_INVITE_ACCEPTED_SUCCESS";

export const OPPORTUNITY_CONTACT_CREATE = "OPPORTUNITY_CONTACT_CREATE";
export const OPPORTUNITY_CONTACT_CREATE_FAIL =
  "OPPORTUNITY_CONTACT_CREATE_FAIL";
export const OPPORTUNITY_CONTACT_CREATE_RESET =
  "OPPORTUNITY_CONTACT_CREATE_RESET";
export const OPPORTUNITY_CONTACT_CREATE_SUCCESS =
  "OPPORTUNITY_CONTACT_CREATE_SUCCESS";

export const OPPORTUNITY_CONTACT_EDIT = "OPPORTUNITY_CONTACT_EDIT";
export const OPPORTUNITY_CONTACT_EDIT_FAIL = "OPPORTUNITY_CONTACT_EDIT_FAIL";
export const OPPORTUNITY_CONTACT_EDIT_RESET = "OPPORTUNITY_CONTACT_EDIT_RESET";
export const OPPORTUNITY_CONTACT_EDIT_SUCCESS =
  "OPPORTUNITY_CONTACT_EDIT_SUCCESS";
