export const PRODUCT_LIST = "PRODUCT_LIST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_LIST_SUBCATEGORIES = "PRODUCT_LIST_SUBCATEGORIES";
export const PRODUCT_LIST_SUBCATEGORIES_SUCCESS =
  "PRODUCT_LIST_SUBCATEGORIES_SUCCESS";
export const PRODUCT_LIST_SUBCATEGORIES_FAIL =
  "PRODUCT_LIST_SUBCATEGORIES_FAIL";
