export const RATING_GET_QUALITY = "RATING_GET_QUALITY";
export const RATING_GET_QUALITY_SUCCESS = "RATING_GET_QUALITY_SUCCESS";
export const RATING_GET_QUALITY_FAIL = "RATING_GET_QUALITY_FAIL";

export const RATING_ADD_QUALITY = "RATING_ADD_QUALITY";
export const RATING_ADD_QUALITY_SUCCESS = "RATING_ADD_QUALITY_SUCCESS";
export const RATING_ADD_QUALITY_FAIL = "RATING_ADD_QUALITY_FAIL";

export const RATING_ADD_RELEVANCY = "RATING_ADD_RELEVANCY";
export const RATING_ADD_RELEVANCY_SUCCESS = "RATING_ADD_RELEVANCY_SUCCESS";
export const RATING_ADD_RELEVANCY_FAIL = "RATING_ADD_RELEVANCY_FAIL";
