export const SNACKBAR_ADD_MESSAGE_QUEUE = "SNACKBAR_ADD_MESSAGE_QUEUE";
export const SNACKBAR_CLEAR_MESSAGE_QUEUE = "SNACKBAR_CLEAR_MESSAGE_QUEUE";
export const SNACKBAR_SHOW_MESSAGE_SUCCESS = "SNACKBAR_SHOW_MESSAGE_SUCCESS";
