export const ACCESS_TOKEN = "ACCESS_TOKEN";
export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const USER_ID = "USERID";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";

export const USER_REFRESH_TOKEN = "USER_REFRESH_TOKEN";
export const USER_REFRESH_TOKEN_SUCCESS = "USER_REFRESH_TOKEN_SUCCESS";
export const USER_REFRESH_TOKEN_FAIL = "USER_REFRESH_TOKEN_FAIL";

export const USER_GET = "USER_GET";
export const USER_GET_SUCCESS = "USER_GET_SUCCESS";
export const USER_GET_FAIL = "USER_GET_FAIL";

export const USER_FETCH_LIST = "USER_FETCH_LIST";
export const USER_FETCH_LIST_SUCCESS = "USER_FETCH_LIST_SUCCESS";
export const USER_FETCH_LIST_FAIL = "USER_FETCH_LIST_FAIL";

export const USER_UPDATE = "USER_UPDATE";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_RESET = "USER_UPDATE_RESET";

export const USER_ADD_DEVICE = "USER_ADD_DEVICE";
export const USER_ADD_DEVICE_FAIL = "USER_ADD_DEVICE_FAIL";
export const USER_ADD_DEVICE_SUCCESS = "USER_ADD_DEVICE_SUCCESS";

export const USER_DELETE_DEVICE = "USER_DELETE_DEVICE";
export const USER_DELETE_DEVICE_FAIL = "USER_DELETE_DEVICE_FAIL";
export const USER_DELETE_DEVICE_SUCCESS = "USER_DELETE_DEVICE_SUCCESS";

export const USER_LINKEDIN_LOGIN_URL = "USER_LINKEDIN_LOGIN_URL";
export const USER_LINKEDIN_LOGIN_URL_FAIL = "USER_LINKEDIN_LOGIN_URL_FAIL";
export const USER_LINKEDIN_LOGIN_URL_SUCCESS =
  "USER_LINKEDIN_LOGIN_URL_SUCCESS";
export const USER_LINKEDIN_LOGIN_URL_RESET = "USER_LINKEDIN_LOGIN_URL_RESET";

export const USER_LINKEDIN_LOGIN = "USER_LINKEDIN_LOGIN";
export const USER_LINKEDIN_LOGIN_FAIL = "USER_LINKEDIN_LOGIN_FAIL";
export const USER_LINKEDIN_LOGIN_SUCCESS = "USER_LINKEDIN_LOGIN_SUCCESS";

export const USER_APPLE_LOGIN = "USER_APPLE_LOGIN";
export const USER_APPLE_LOGIN_CANCELLED = "USER_APPLE_LOGIN_CANCELLED";
export const USER_APPLE_LOGIN_FAIL = "USER_APPLE_LOGIN_FAIL";
export const USER_APPLE_LOGIN_SUCCESS = "USER_APPLE_LOGIN_SUCCESS";

export const USER_RESET_PASSWORD = "USER_RESET_PASSWORD";
export const USER_RESET_PASSWORD_FAIL = "USER_RESET_PASSWORD_FAIL";
export const USER_RESET_PASSWORD_SUCCESS = "USER_RESET_PASSWORD_SUCCESS";
export const USER_RESET_PASSWORD_STATUS_RESET =
  "USER_RESET_PASSWORD_STATUS_RESET";

export const USER_RESET_PASSWORD_CONFIRMATION =
  "USER_RESET_PASSWORD_CONFIRMATION";
export const USER_RESET_PASSWORD_CONFIRMATION_SUCCESS =
  "USER_RESET_PASSWORD_CONFIRMATION_SUCCESS";
export const USER_RESET_PASSWORD_CONFIRMATION_FAIL =
  "USER_RESET_PASSWORD_CONFIRMATION_FAIL";

export const USER_GOOGLE_LOGIN = "USER_GOOGLE_LOGIN";
export const USER_GOOGLE_LOGIN_CANCELLED = "USER_GOOGLE_LOGIN_CANCELLED";
export const USER_GOOGLE_LOGIN_FAIL = "USER_GOOGLE_LOGIN_FAIL";
export const USER_GOOGLE_LOGIN_SUCCESS = "USER_GOOGLE_LOGIN_SUCCESS";

export const USER_GOOGLE_LOGOUT = "USER_GOOGLE_LOGOUT";
export const USER_GOOGLE_LOGOUT_FAIL = "USER_GOOGLE_LOGOUT_FAIL";
export const USER_GOOGLE_LOGOUT_SUCCESS = "USER_GOOGLE_LOGOUT_SUCCESS";

export const USER_GET_LOGIN_METHODS = "USER_GET_LOGIN_METHODS";
export const USER_GET_LOGIN_METHODS_FAIL = "USER_GET_LOGIN_METHODS_FAIL";
export const USER_GET_LOGIN_METHODS_RESET = "USER_GET_LOGIN_METHODS_RESET";
export const USER_GET_LOGIN_METHODS_SUCCESS = "USER_GET_LOGIN_METHODS_SUCCESS";

export const USER_SIGNUP = "USER_SIGN_UP";
export const USER_SIGNUP_SUCCESS = "USER_SIGN_UP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGN_UP_FAIL";

export const USER_SIGNUP_CONFIRMATION = "USER_SIGN_UP_CONFIRMATION";
export const USER_SIGNUP_CONFIRMATION_SUCCESS =
  "USER_SIGN_UP_CONFIRMATION_SUCCESS";
export const USER_SIGNUP_CONFIRMATION_FAIL = "USER_SIGN_UP_CONFIRMATION_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_DELETE_ACCOUNT = "USER_DELETE_ACCOUNT";
export const USER_DELETE_ACCOUNT_SUCCESS = "USER_DELETE_ACCOUNT_SUCCESS";
export const USER_DELETE_ACCOUNT_FAIL = "USER_DELETE_ACCOUNT_FAIL";

export const USER_SET_LOGIN_ACTION = "USER_SET_LOGIN_ACTION";
